name: movie_app
description: "Movies Database App - Trending & Now Playing Movies with TMDB API"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.4.0
  retrofit: ^4.0.3
  json_annotation: ^4.9.0
  provider: ^6.1.1
  sqflite: ^2.3.0
  path: ^1.8.3
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  url_launcher: ^6.2.2
  share_plus: ^7.2.2
  logger: ^2.2.0
  toastification: ^2.0.0
  flutter_dotenv: ^5.1.0
  go_router: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - .env
